### ISSUE TITLE
Avoid notice: Undefined index: #type in oe_whitelabel_search_preprocess_facets_summary_item_list

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/oe_whitelabel#165]
I'm having this error:

```
Notice: Undefined index: #type in oe_whitelabel_search_preprocess_facets_summary_item_list() (line 45 of themes/contrib/oe_whitelabel/modules/oe_whitelabel_search/oe_whitelabel_search.module).
```

The problem occurs here:
https://github.com/openeuropa/oe_whitelabel/blob/1.0.0-beta3/modules/oe_whitelabel_search/oe_whitelabel_search.module#L45
By the way, the $item[#theme] is "facets_summary_count".

In any case, checking if ``` isset($item['value']['#type']) ``` , before checking its actual value, would fix the problem with no harm, that's my simple proposed solution.

**Comment by brummbar** [comment]
Fixed in beta4 release.
