### ISSUE TITLE
EU and EC logos are missing from the oe_bootstrap_theme artifact.

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_whitelabel#169]
Hello, 
For UCPKN, after updating the base theme to 1.0.0-beta4, the EU logo is not displayed anymore both in header and footer. This is because oe_bootstrap_theme artifact is no longer containing the EC/EU logos!
Here oe_whitelabel_theme is expecting the logos are provided by the oe_bootstrap_theme https://github.com/openeuropa/oe_whitelabel/blob/1.0.0-beta4/oe_whitelabel.theme#L56

**Comment by brummbar** [comment]
Isn't this bug for oe_bootstrap_theme then?

**Comment by brummbar** [comment]
Issue confirmed, we will re-roll soon a new bootstrap release.

**Comment by brummbar** [comment]
Released [oe_bootstrap_theme 1.0.0-beta4](https://github.com/openeuropa/oe_bootstrap_theme/releases/tag/1.0.0-beta4) which contains the missing icons. Thanks for reporting this @msnassar !
