### ISSUE TITLE
Allow current path as action in the form of SearchBlock

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/oe_whitelabel#180]
I propose to let the action to not be required here:
https://github.com/openeuropa/oe_whitelabel/blob/1.0.0-beta5/modules/oe_whitelabel_search/src/Plugin/Block/SearchBlock.php#L121

If so, the current path (`\Drupal::service('path.current')->getPath();`) should be use for the action of the form.

This is a very common case, to have the form submitting to the current page.

This solves a more complex problem, when the action has some tokens in it.
Currently, if action is something like "groups/%group/members" how can we set the action properly in the block?

**Comment by brummbar** [comment]
Not planned at the moment, it could lead to a series of problems for which we don't have a use case now. This can be achieved with a simple form alter and replacing the submit callback directly on the project code.
