### ISSUE TITLE
CKEditor stylesheet referenced in info file doesn't exist

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_whitelabel#184]
Currently using OE Whitelabel version 1.0.0-beta3, but I think the issue still exists on the latest version. 

The oe_whitelabel.info.yml file is referencing a ckeditor stylesheet that doesn't exist: https://github.com/openeuropa/oe_whitelabel/blob/1.0.0-beta5/oe_whitelabel.info.yml#L18

I discovered this when I saw this error in the console on pages where ckeditor is loaded:
`Refused to apply style from './themes/contrib/oe_whitelabel/assets/css/oe-bcl-default.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Note: the css file seem to exist in the OE Bootstrap Theme on that path.

**Comment by kp77** [comment]
Checked it, the issue exists also on beta5.

**Comment by brummbar** [comment]
Fixed in #192, will be released in beta8.
