### ISSUE TITLE
Pass block's attributes to offcanvas pattern for block--facets-form.html.twig

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_whitelabel#210]
We would like to hide the facets form when all facets are hidden. In order to do that -as a workaround- we preprocess the facets form block and set 'd-none' class when the condition is met. But the class is not added to the block. This is because the block's template doesn't pass the attributes to the offcanvas pattern!

It would be nice to have settings for the facets form to hide the form when all facets are hidden https://www.drupal.org/project/facets_form/issues/3344978. Similar issues:
Facets: https://www.drupal.org/project/facets/issues/2984465
Facets block: https://www.drupal.org/project/facets_block/issues/3207373

**Comment by tibi2303** [comment]
Hello,
Indeed, I see now the form should be hidden if there are no facets.
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/36895476/225254865-ac06aecd-0ae7-4b4b-a8a2-cb4b19564e05.png">
But the whole layout should be changed, no? What i mean is that if the sidebar is hidden when there are no facets the content area should grow to full size 'col-12'.

**Comment by brummbar** [comment]
Will be fixed in #237 .
