### ISSUE TITLE
Fix spacing for search icon in header search block

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_whitelabel#246]
In small breakpoint there is a space to the right of the search icon. This issue has been initially reported in https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-2602 and handled in https://github.com/openeuropa/oe_whitelabel/pull/240/files

However, after we update the theme to the recent version (1.4), we still have space. See below a screenshot.
![image](https://github.com/openeuropa/oe_whitelabel/assets/15343499/82d46415-4ab1-49b3-ab52-151878296f6a)

**Proposed solution:**
- To avoid this undesirable space to the right of the icon in the small breakpoints, I think it is better to add the margin to the "Search" text instead. This is because, we keep displaying the icon in all breakpoints and hide the text in small breakpoints.

**Comment by drishu** [comment]
these issue is not relevant anymore as we have new accessibility requirements for this, see https://github.com/openeuropa/oe_whitelabel/pull/314
