### ISSUE TITLE
Reduce text in README.md about docker-compose

### ISSUE THREAD

**Issue by donquixote** [openeuropa/oe_whitelabel#280]
Most of the openeuropa packages need docker-compose to set up the local development instance.
It is a bit pointless to repeat this in README.md, of every package.

Instead, there could be a centralized (public!) documentation about the use of docker-compose in openeuropa projects, and then the instructions can be reduced.

**Comment by brummbar** [comment]
The documentation needs for sure to be updated, but there is no plan to centralize it.
