### ISSUE TITLE
oe_project_budget fields deleted in oe_content 4.0

### ISSUE THREAD

**Issue by Aporie** [openeuropa/oe_whitelabel#303]
Hello,

2 fields were deleted in [oe_content 4.0](https://github.com/openeuropa/oe_content/pull/622/files#diff-dea75a63e555ef29136054629f00c42d38c8e669980e1b9e09592a96123dbf02R82). This currently leads to the following error when trying to view a project page without restoring these two fields:

```
The website encountered an unexpected error. Try again later.

InvalidArgumentException: Field oe_project_budget is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 616 of core/lib/Drupal/Core/Entity/ContentEntityBase.php).
Drupal\Core\Entity\ContentEntityBase->get() (Line: 64)
Drupal\oe_whitelabel_extra_project\Plugin\ExtraField\Display\BudgetExtraFieldBase->viewElements() (Line: 46)
Drupal\extra_field\Plugin\ExtraFieldDisplayFormattedBase->view() (Line: 122)
Drupal\extra_field\Plugin\ExtraFieldDisplayManager->entityView() (Line: 29)
extra_field_entity_view()
```

The two methods to handle deprecated fields can now safely be removed:

in oe_whitelabel_extra_project/Plugin/ExtraField/Display/BudgetExtraFieldBase
in oe_whitelabel_extra_project/Plugin/ExtraField/Display/OverallBudgetExtraField

Logic in oe_whitelabel_extra_project/Plugin/ExtraField/Display/BudgetExtraFieldBase can be simplified.

Patch attached: 
[oe_whitelabel_remove_oe_content_deprecated_fields.txt](https://github.com/user-attachments/files/16600981/oe_whitelabel_remove_oe_content_deprecated_fields.txt)

**Comment by drishu** [comment]
We did not upgrade to 4.x yet, any issue should be reported after we do
