### ISSUE TITLE
The header pattern displays an empty navbar when both regions are empty

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_whitelabel#50]
If both the Header left and Header right regions are empty, the header pattern still displays an empty navbar.

![image](https://user-images.githubusercontent.com/648045/142903004-f3a1ac97-b7a5-4d64-950f-afeeddf4b171.png)

Currently I'm fixing this by overriding `/templates/patterns/header/pattern-header.html.twig` and adding this conditional in the override template:

```
  {% if header_left is not empty or header_right is not empty %}
    {% block content %}
      {{ content }}
    {% endblock %}
  {% endif %}
```
See: https://github.com/openeuropa/oe_whitelabel/blob/1.x/templates/patterns/header/pattern-header.html.twig#L40-L42

**Comment by brummbar** [comment]
We removed the header pattern as not useful.
