### ISSUE TITLE
EU logo is not displayed on mobile

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_whitelabel#95]
After updating to 1.0.0-alpha5, the EU logo is not displayed on mobile screens. This is because the output from CorporateEuLogoBlock is not compatible with the BCL markup. Responsive classes were added to the logo image, but the mobile logo image is missing.

See:
https://v0-19-0--oelibrary.netlify.app/default/?path=/story/compositions-header--header

https://github.com/openeuropa/oe_whitelabel/blob/1.0.0-alpha5/modules/oe_whitelabel_helper/src/Plugin/Block/CorporateEuLogoBlock.php#L84-L103

**Comment by brummbar** [comment]
Is this still valid @kp77 ?

**Comment by kp77** [comment]
Hi @brummbar,

Not sure yet, as we are still using alpha5 version. I see in alpha6 the whole header was refactored see: #71, and the block mentioned above was removed. So this specific issue probably doesn't exist anymore. We will need to check after updating.

**Comment by brummbar** [comment]
Thanks, I'll keep it open then and we see later.

**Comment by msnassar** [comment]
Hello @brummbar 
The issue is not valid anymore after theme update (1.0.0-beta3)
